name: ticketcinema

services:
  backend:
    build:
      context: ./mainBackend/be-src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    container_name: ticketcinema-backend
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=kien123456
      - MYSQL_DATABASE=ticketdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: ticketcinema-mysql
    restart: unless-stopped

volumes:
  mysql-data: