version: '3.8'

services:
  backend:
    image: ticketcinema-backend
    build:
      context: ./mainProject/mainBackend/be-src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.1.51:3306/ticketDB?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
      - SPRING_DATASOURCE_USERNAME=root
      - VNPAY_TMN_CODE=S9J1L8QI
    container_name: ticketcinema-backend
    restart: unless-stopped